### PR TITLE
cli to re-enable all disabled workflows

### PR DESCRIPTION
**Pull request by ivy-rew**
- handy to re-enable all market builds, e.g. before a major release

### CODE REVIEW

**Review by ivy-lli — COMMENTED** [review]
Why do you not use the gh cli?
Then you don't even need to get a token as you are already logged in with the cli...

https://cli.github.com/manual/gh_run

**Comment by ivy-rew** [comment]
> Why do you not use the gh cli? Then you don't even need to get a token as you are already logged in with the cli...
> 
> https://cli.github.com/manual/gh_run

hmm cool idea to simplify the curl requests via `gh api`.
at least for those users already running it, for others it may be much simpler to use the browser to lease it :wink: 

let me refactor and see how it works.

**Comment by ivy-lli** [comment]
> > Why do you not use the gh cli? Then you don't even need to get a token as you are already logged in with the cli...
> > https://cli.github.com/manual/gh_run
> 
> hmm cool idea to simplify the curl requests via `gh api`. at least for those users already running it, for others it may be much simpler to use the browser to lease it 😉
> 
> let me refactor and see how it works.

I think the code would be simpler, and we use the gh cli already in the github manager repo scripts so... But only as a suggestion.

**Comment by ivy-rew** [comment]
> > > Why do you not use the gh cli? Then you don't even need to get a token as you are already logged in with the cli...
> > > https://cli.github.com/manual/gh_run
> > 
> > 
> > hmm cool idea to simplify the curl requests via `gh api`. at least for those users already running it, for others it may be much simpler to use the browser to lease it 😉
> > let me refactor and see how it works.
> 
> I think the code would be simpler, and we use the gh cli already in the github manager repo scripts so... But only as a suggestion.

checked it again; 
it seems like gh even supports our use-cases pretty well with native commands.
so I'll rewrite it ... given time :wink:  so I merge it for now as is.

**Pull request merged**
